/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        cairo: ['Cairo', 'sans-serif'],
        tajawal: ['Tajawal', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
      },
      colors: {
        brand: {
          gold:        '#0D9B7A',
          'gold-h':    '#0FB08B',
          'gold-dim':  'rgba(13,155,122,0.12)',
          'gold-bdr':  'rgba(13,155,122,0.30)',
          'gold-glo':  'rgba(13,155,122,0.25)',
          teal:        '#5C67E6',
          'teal-h':    '#738AF7',
          'teal-dim':  'rgba(92,103,230,0.10)',
          'teal-bdr':  'rgba(92,103,230,0.28)',
          'teal-glo':  'rgba(92,103,230,0.22)',
          danger:      '#FF4F6E',
        },
        // Semantic tokens — map to CSS custom properties set by data-theme
        v3: {
          bg:       'var(--bg)',
          bg2:      'var(--bg2)',
          bg3:      'var(--bg3)',
          surface:  'var(--surface)',
          surface2: 'var(--surface2)',
          border:   'var(--border)',
          border2:  'var(--border2)',
          border3:  'var(--border3)',
          text:     'var(--text)',
          text2:    'var(--text2)',
          text3:    'var(--text3)',
        },
        primary: {
          50:  '#f5f7ff',
          100: '#ebf0fe',
          200: '#ced9fd',
          300: '#a3b5fa',
          400: '#738af7',
          500: '#5c67e6',
          600: '#4a51ca',
          700: '#3c40a5',
          800: '#323485',
          900: '#2c2e6f',
          950: '#1a1b41',
        },
      },
      animation: {
        'slide-up':    'slideUp 0.4s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
        'slide-left':  'slideLeft 0.3s ease-out',
        'fade-in':     'fadeIn 0.3s ease-out',
        'pulse-soft':  'pulseSoft 2s infinite',
        'float':       'float 4s ease-in-out infinite',
      },
      keyframes: {
        slideUp:    { '0%': { opacity: 0, transform: 'translateY(20px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        slideRight: { '0%': { opacity: 0, transform: 'translateX(-20px)' }, '100%': { opacity: 1, transform: 'translateX(0)' } },
        slideLeft:  { '0%': { opacity: 0, transform: 'translateX(20px)' }, '100%': { opacity: 1, transform: 'translateX(0)' } },
        fadeIn:     { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        pulseSoft:  { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0.7 } },
        float:      { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-7px)' } },
      },
    },
  },
  plugins: [],
};
